# Generated by Django 4.0.6 on 2022-07-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('is_verified', models.BooleanField()),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=250)),
                ('expired_date', models.DateField()),
                ('is_completed', models.BooleanField()),
                ('usertodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_todo.userdetails')),
            ],
            options={
                'db_table': 'UserTodo',
            },
        ),
    ]
