# Generated by Django 4.0.5 on 2022-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0006_alter_userdetails_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
